'use strict';
module.exports = {
  CLI_DEFAULT_COMMAND: `--help`,
  CLI_ARGS_INDEX: 2,
  DEFAULT_PORT: 3000,
  HTTP_CODE: {
    SUCCESS: 200,
    NOT_FOUND: 404
  },
  FILE_SIZE_MIN: 1,
  FILE_SIZE_MAX: 1000,
  FILE_NAME: `mocks.json`,
  ANNOUNCE_MAX: 1,
  FULL_TEXT_MAX: 5,
  CREATED_DATE_MIN: 3,
  MONTH_MILLISECONDS: 2592000000,
  EXIT_CODE: {
    SUCCESS: 0,
    ERROR: 1
  }
};
